server:
  port: 8080 # springboot服务对外端口号

spring:
  redis:
    database: 0
    timeout: 3000
    sentinel: #哨兵模式
      master: mymaster #主服务器所在集群名称
      nodes: 192.168.48.144:26379,192.168.48.144:26380,192.168.48.144:26381
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000