server:
  port: 7001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 957ilovemyfamily
    url: jdbc:mysql://localhost:3306/practice?serverTimezone=GMT%2B8
  redis:
    password: 123456
