spring:
  data:
    mongodb:
      uri: mongodb://yujin:yujin@192.168.48.144:27017/test?authSource=admin
      #uri等同于下面的配置
      #database: test
      #host: 192.168.65.174
      #port: 27017
      #username: fox
      #password: fox
      #authentication-database: admin